namespace HrevertCRM.Entities
{
    public enum EntityId
    {
        Account = 1,
        Address = 2,
        Company = 3,
        CustomerContactGroup = 4,
        Customer = 5,
        CustomerLevel = 6,
        DeliveryMethod = 7,
        PaymentMethod = 8,
        PaymentTerm = 9,
        Carousel = 10,
        ECommerceSetting = 11,
        EmailSetting = 12,
        FiscalPeriod = 13,
        FiscalYear = 14,
        JournalMaster = 15,
        ProductCategory = 16,
        Product = 17,
        ProductMetadata = 18,
        ProductPriceRule = 19,
        PurchaseOrder = 20,
        PurchaseOrderLine = 21,
        SalesOrder = 22,
        SalesOrderLine = 23,
        Tax = 24,
        Security = 25,
        SecurityGroup = 26,
        SecurityGroupMember = 27,
        SecurityRight = 28,
        TransactionLog = 29,
        DeliveryRate = 30,
        DeliveryZone = 31,
        ItemMeasure = 32,
        MeasureUnit = 33,
        ShoppingCart = 34,
        User = 35,
        Vendor = 36,
        CompanyWebSetting = 37,
        Discount = 38,
        FeaturedItem = 39,
        FeaturedItemMetadata = 40,
        BugLogger = 41,
        CompanyLogo = 42,
        Country = 43

    }
}
